// DOM element references
export const elements = {
    chatWindow: document.getElementById('chat-window'),
    userInput: document.getElementById('user-input'),
    sendButton: document.getElementById('send-button'),
    llmProvider: document.getElementById('llm-provider'),
    llmModel: document.getElementById('llm-model'),
    llmStatus: document.getElementById('llm-status'),
    imageUpload: document.getElementById('image-upload'),
    uploadButton: document.getElementById('upload-button'),
    darkModeToggle: document.getElementById('dark-mode-toggle'),
    sidebar: document.querySelector('.sidebar'),
    inputWithUpload: document.querySelector('.input-with-upload'),
    formSelects: document.querySelectorAll('.form-group select'),
    resetButton: document.getElementById('reset-button'),
    stopButton: document.getElementById('stop-button'),
    sidebarToggle: document.getElementById('sidebar-toggle'),
    systemMessageTextarea: document.getElementById('system-message'),
    conversationList: document.getElementById('conversation-list'),
    deleteAllConversationsButton: document.getElementById('delete-all-conversations-button'),
    systemMessageSelect: document.getElementById('system-message-select'),
    saveSystemMessageButton: document.getElementById('save-system-message-button'),
    deleteSystemMessageButton: document.getElementById('delete-system-message-button'),
    toolsContainer: document.getElementById('tools-container'),
    activeToolsContainer: document.getElementById('active-tools-container'),
    thinkToggle: document.getElementById('think-toggle'),
    thinkDepth: document.getElementById('think-depth'),
    thinkDepthMessage: document.getElementById('think-depth-message'),
    openaiBaseUrlGroup: document.getElementById('openai-base-url-group'),
    openaiBaseUrlInput: document.getElementById('openai-base-url'),
    showConversationsButton: document.getElementById('show-conversations-button'),
    conversationsModal: document.getElementById('conversations-modal'),
    conversationsListModal: document.getElementById('conversations-list-modal'),
    closeModalButton: document.querySelector('.close-button'),
    deleteAllTasksButton: document.getElementById('delete-all-tasks-button'),
    taskResponseModal: document.getElementById('task-response-modal'),
    taskResponseContent: document.getElementById('task-response-content'),
    tokensPerSecondDisplay: document.getElementById('tokens-per-second')
};