import ollama
from typing import List, Optional, Generator
from PIL import Image
import io
import json
import sys

class Think:
    def __init__(self):
        self.available_models = self._list_available_models("ollama")

    def _list_available_models(self, provider) -> List[str]:
        """
        Lists available models in the Ollama API.

        Returns:
            List[str]: Lista con los nombres de los modelos disponibles.
        """
        try:
            models = ollama.list()
            print(f"Ollama models response: {models}")
            return [model.model for model in models['models']]
        except Exception as e:
            print(f"Error listing Ollama models: {e}")
            return []

    def generate_response(
        self,
        prompt: str,
        model_name: str,
        provider: str,
        image: Optional[Image.Image] = None,
        history: Optional[List[dict]] = None,
        system_message: Optional[str] = None,
        depth: int = 1
    ) -> Generator[str, None, None]:
        """
        Generates a response using the specified Ollama model, iterating 'depth' times,
        and returning blocks of text iteratively.

        Args:
            prompt (str): Input prompt.
            model_name (str): Name of the Ollama model to use.
            provider (str): Name of the provider.
            image (Optional[Image.Image]): Optional image that can be included in the prompt.
            history (Optional[List[dict]]): Previous message history.
            system_message (Optional[str]): System message that can be included in the prompt.
            depth (int): Number of iterations.

        Yields:
            str: Fragments of the response generated by Ollama.
        """
        try:
            messages = []
            if system_message:
                messages.append({"role": "system", "content": system_message})
            if history:
                for message in history:
                    if message["role"] == "model":
                        messages.append({"role": "assistant", "content": message["content"]})
                    else:
                        messages.append({"role": message["role"], "content": message["content"]})

            if image:
                # Convert PIL image to bytes
                image_bytes = io.BytesIO()
                image.save(image_bytes, format=image.format if image.format else "PNG")
                image_bytes = image_bytes.getvalue()

                messages.append({"role": "user", "content": prompt, "images": [image_bytes]})
            else:
                messages.append({"role": "user", "content": prompt})

            # Ensure we only use the model name (separated by :)
            model_name = model_name.split(":")[0]

            final_prompt = prompt  # Initialize with the original prompt

            for i in range(depth):
                print(f"\n--- Iteration #{i + 1} of {depth} ---")

                if i > 0:
                    final_prompt = f"{prompt}\nWait, I have to think it again..."

                # Clear the message history before each iteration
                messages = messages[:2] if system_message else []
                messages.append({"role": "user", "content": final_prompt})

                # Make the call to Ollama
                # TODO: Use the provider to call the model
                response_stream = ollama.chat(model=model_name, messages=messages, stream=True)
                for chunk in response_stream:
                    yield chunk['message']['content']

        except Exception as e:
            yield f"Error generating response: {e}"


